inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: true
  Exclude: ['spec/**/*', 'apps/**/*']

AllCops:
  TargetRubyVersion: 2.2
